/**
 * Static image imports (`import img from "@/app/opengraph-image.png"`) rely on the ambient
 * module declarations from `next/image-types/global`. `next-env.d.ts` references them but is
 * generated by `next dev`/`next build` and gitignored, so a fresh checkout running `tsc --noEmit`
 * before any build (CI's typecheck job) has no `*.png` module types. Keep the reference in a
 * tracked file so typecheck is the same locally and in CI (T-M8-433 follow-up, 2026-09-05).
 */
/// <reference types="next/image-types/global" />
